### ISSUE TITLE
Prodigy optimizer cannot be resumed from checkpoint

### ISSUE THREAD

**Issue by Vectorrent** [kozistr/pytorch_optimizer#266]
## Describe the bug

When trying to resume training from a saved Pytorch Lightning checkpoint, the Prodigy optimizer fails with the following:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!
```
This error does not occur with other optimizers, such as Lion. A Lion checkpoint can be restored without any trouble.

After briefly inspecting the Prodigy and Lion code, I suspect this might be the problem:
```py
group = self.param_groups[0]
device = group['params'][0].device

d_de_nom = torch.tensor([0.0], device=device)
```
The Prodigy code makes references to specific devices, while Lion does not. 

## To Reproduce

* OS : Linux
* PyTorch version : 2.2.2
* pytorch-lightning version: pytorch-lightning
* Python version : 3.10.12
* pytorch_optimizer version: 3.0.1
* reproducible codes : TBD

## Log
```
Traceback (most recent call last):
  File "/src/harness.py", line 434, in <module>
    main()
  File "/src/harness.py", line 233, in main
    prototype.train(
  File "/src/aigen/aigen/aigen.py", line 745, in train
    trainer.fit(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
    self.advance()
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
    self.advance(data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/training_epoch_loop.py", line 250, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 190, in run
    self._optimizer_step(batch_idx, closure)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/loops/optimization/automatic.py", line 268, in _optimizer_step
    call._call_lightning_module_hook(
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/module.py", line 1303, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/core/optimizer.py", line 152, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/strategies/strategy.py", line 239, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/pytorch/plugins/precision/precision.py", line 122, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_optimizer/optimizer/prodigy.py", line 136, in step
    d_numerator.add_(torch.dot(grad.flatten(), (p0 - p).flatten()), alpha=(d / d0) * d_lr)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!
```

## Expected behavior

I would expect all optimizers to be serializable, and restore-able from disk. I would not expect a checkpoint to load an optimizer onto the wrong device.

## Additional context

I do not have reproducible code readily available, but I can provide that code - if you need it. Just let me know if you do. Otherwise, I might dig into this problem at some point, and try to fix it myself. Thanks!

**Comment by kozistr** [comment]
thanks for reporting! I'll look into it

**Comment by kozistr** [comment]
device mismatch error happens in `d_numerator.add_(torch.dot(grad.flatten(), (p0 - p).flatten()), alpha=(d / d0) * d_lr)` and the right ones (e.g. grad, p, p0) must be on the GPU if trained on the GPU, then `d_numerator` could be a problem. 

I found the bug that the device of the `d_numerator` is only determined at the initialization and I causes the device mismatch problem. I'll make a PR to fix this bug

**Comment by kozistr** [comment]
in the meantime, Ali-G, D-Adapt also have a same problem, so also fixed too

**Comment by Vectorrent** [comment]
> @Vectorrent
> 
> in the meantime, Ali-G, D-Adapt also have a same problem, also fixed too.
> 
>     * The fix is merged into the main branch! could you please check if the fix is valid if you are available?

Just tested the latest version, and it works! That fixed my problem.

I appreciate the quick response!
