### ISSUE TITLE
Cannit run with adam_mini

### ISSUE THREAD

**Issue by atonyo11** [kozistr/pytorch_optimizer#293]
## Describe the bug
I tried to run my program with AdamMini

## To Reproduce

* OS : (e.g. Linux)
* PyTorch version : 2.0.1, cuda 11.8
* Python version :  3,9
* reproducible codes :
`
        elif self.optim_dict["optimizer"] == 'AdamMini':
            alpha = self.optim_dict['learning_ratio']
            self.optimizer = AdamMini(
                model.parameters(),
                lr=self.optim_dict['base_lr'],
                weight_decay=self.optim_dict['weight_decay']
            )  
`

## Log

`
Traceback (most recent call last):
  File "/private/opti-corrnet/main.py", line 258, in <module>
    processor = Processor(args)
  File "/private/opti-corrnet/main.py", line 52, in __init__
    self.model, self.optimizer = self.loading()
  File "/private/opti-corrnet/main.py", line 140, in loading
    optimizer = utils.Optimizer(model, self.arg.optimizer_args)
  File "/private/opti-corrnet/utils/optimizer.py", line 34, in __init__
    self.optimizer = AdamMini(
  File "/secret/.conda/envs/corrnet/lib/python3.9/site-packages/pytorch_optimizer/optimizer/adam_mini.py", line 63, in __init__
    groups = self.get_optimizer_groups(weight_decay)
  File "/secret/.conda/envs/corrnet/lib/python3.9/site-packages/pytorch_optimizer/optimizer/adam_mini.py", line 73, in get_optimizer_groups
    for name, param in self.model.named_parameters():
AttributeError: 'generator' object has no attribute 'named_parameters'
`

**Comment by atonyo11** [comment]
Does error by my code or by pytorch_optimizer?

**Comment by kozistr** [comment]
@atonyo11 hi. `AdamMini` takes `nn.Module` instance instead of the `parameters`. So, you should pass `model` instead of `model.parameters()`.

```python
optimizer = AdamMini(model=model, lr=self.optim_dict['base_lr'], weight_decay=self.optim_dict['weight_decay'])
```

you can check [the documentation](https://pytorch-optimizers.readthedocs.io/en/latest/optimizer/#pytorch_optimizer.AdamMini) for AdamMini optimizer.

**Comment by atonyo11** [comment]
Ah, I got it. Thank you very much!
